[workspace]
resolver = "2"
members = [
    "harness",
    "hwbp-hooks",
    "common",
    "syscall",
]

[profile.release]
opt-level = "z"
debug = false
strip = true
debug-assertions = false
overflow-checks = false
lto = true
panic = "abort"
incremental = false
codegen-units = 1
rpath = false