[package]
name = "importer"
version = "0.1.0"
edition = "2024"

[dependencies]
utilities = { path = "../utilities" }
windows-core = { git = "https://github.com/microsoft/windows-rs.git" }

[build-dependencies]
windows-bindgen = { git = "https://github.com/microsoft/windows-rs.git" }

[lints]
workspace = true