[package]
name = "runner"
version = "0.1.0"
edition = "2024"

[dependencies]
importer = { path = "../importer" }
utilities = { path = "../utilities" }

[lints]
workspace = true

# [build]
# rustflags = ["-C", "link-arg=/NODEFAULTLIB"]

# [target.'cfg(all(windows, target_env = "msvc"))']
# unstable.build-std = ["core", "compiler_builtins"]
# unstable.build-std-features = ["compiler-builtins-mem"]